export const menuList = [
  // Common menus (appear in multiple portals)
  {
    id: 1,
    name: "dashboard",
    path: "#",
    icon: "feather-home",
    dropdownMenu: false,
    roles: ["superadmin", "admin"],
    portals: [
      "cms",
      "eduroam",
      "dns",
      "user-management",
      "web-hosting",
      "email-hosting",
      "ticketing",
    ],
    dropdownMenu: [
      {
        id: 21,
        name: "CMS",
        path: "/cms/dashboard",
        subdropdownMenu: false,
      },
      {
        id: 22,
        name: "Eduroam",
        path: "/eduroam/dashboard",
        subdropdownMenu: false,
      },
      {
        id: 23,
        name: "DNS",
        path: "/dns/dashboard",
        subdropdownMenu: false,
      },
      {
        id: 24,
        name: "Web Hosting",
        path: "/web-hosting/dashboard",
        subdropdownMenu: false,
      },
    ],
  },
  {
    id: 2,
    name: "reports",
    path: "#",
    icon: "feather-cast",
    portals: ["cms"],
    dropdownMenu: [
      {
        id: 21,
        name: "Sales Report",
        path: "/reports/sales",
        subdropdownMenu: false,
      },
      {
        id: 22,
        name: "Leads Report",
        path: "/reports/leads",
        subdropdownMenu: false,
      },
      {
        id: 23,
        name: "Project Report",
        path: "/reports/project",
        subdropdownMenu: false,
      },
      {
        id: 24,
        name: "Timesheets Report",
        path: "/reports/timesheets",
        subdropdownMenu: false,
      },
    ],
  },
  {
    id: 3,
    name: "authentication",
    path: "#",
    icon: "feather-power",
    portals: [
      "cms",
      "eduroam",
      "dns",
      "web-hosting",
      "email-hosting",
      "ticketing",
    ],
    dropdownMenu: [
      {
        id: 31,
        name: "login",
        path: "#",
        subdropdownMenu: [
          { id: 311, name: "Cover", path: "/authentication/login/cover" },
          { id: 312, name: "Minimal", path: "/authentication/login/minimal" },
          { id: 313, name: "Creative", path: "/authentication/login/creative" },
        ],
      },
      {
        id: 32,
        name: "register",
        path: "#",
        subdropdownMenu: [
          { id: 321, name: "Cover", path: "/authentication/register/cover" },
          {
            id: 322,
            name: "Minimal",
            path: "/authentication/register/minimal",
          },
          {
            id: 323,
            name: "Creative",
            path: "/authentication/register/creative",
          },
        ],
      },
      {
        id: 33,
        name: "Error 404",
        path: "#",
        subdropdownMenu: [
          { id: 331, name: "Cover", path: "/authentication/404/cover" },
          { id: 332, name: "Minimal", path: "/authentication/404/minimal" },
          { id: 333, name: "Creative", path: "/authentication/404/creative" },
        ],
      },
      {
        id: 34,
        name: "Reset Pass",
        path: "#",
        subdropdownMenu: [
          { id: 341, name: "Cover", path: "/authentication/reset/cover" },
          { id: 342, name: "Minimal", path: "/authentication/reset/minimal" },
          { id: 343, name: "Creative", path: "/authentication/reset/creative" },
        ],
      },
      {
        id: 35,
        name: "Verify OTP",
        path: "#",
        subdropdownMenu: [
          { id: 351, name: "Cover", path: "/authentication/verify/cover" },
          { id: 352, name: "Minimal", path: "/authentication/verify/minimal" },
          {
            id: 353,
            name: "Creative",
            path: "/authentication/verify/creative",
          },
        ],
      },
      {
        id: 36,
        name: "Maintenance",
        path: "#",
        subdropdownMenu: [
          { id: 361, name: "Cover", path: "/authentication/maintenance/cover" },
          {
            id: 362,
            name: "Minimal",
            path: "/authentication/maintenance/minimal",
          },
          {
            id: 363,
            name: "Creative",
            path: "/authentication/maintenance/creative",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "payment",
    path: "#",
    icon: "feather-dollar-sign",
    portals: ["cms", "ticketing", "web-hosting", "email-hosting"],
    dropdownMenu: [
      {
        id: 41,
        name: "Payment",
        path: "/payment/list",
        subdropdownMenu: false,
      },
      {
        id: 42,
        name: "Invoice View",
        path: "/payment/view",
        subdropdownMenu: false,
      },
      {
        id: 43,
        name: "Invoice Create",
        path: "/payment/create",
        subdropdownMenu: false,
      },
    ],
  },
  {
    id: 5,
    name: "settings",
    path: "/settings",
    icon: "feather-settings",
    dropdownMenu: false,
    roles: ["superadmin"],
    portals: [
      "cms",
      "web-hosting",
      "dns",
      "user-management",
      "email-hosting",
      "ticketing",
    ],
  },

  // Eduroam Portal Menus
  {
    id: 6,
    name: "institutions",
    path: "#",
    icon: "feather-building",
    roles: ["superadmin"],
    portals: ["eduroam"],
    dropdownMenu: [
      {
        id: 61,
        name: "All Institutions",
        path: "/institutions/list",
        subdropdownMenu: false,
      },
      {
        id: 62,
        name: "Add Institution",
        path: "/institutions/add",
        subdropdownMenu: false,
      },
    ],
  },
  {
    id: 7,
    name: "institution admins",
    path: "#",
    icon: "feather-user-check",
    roles: ["superadmin"],
    portals: ["eduroam"],
    dropdownMenu: [
      {
        id: 71,
        name: "All Admins",
        path: "/admins/list",
        subdropdownMenu: false,
      },
      {
        id: 72,
        name: "Add Admin",
        path: "/admins/add",
        subdropdownMenu: false,
      },
    ],
  },

  // User Management Portal Menus
  {
    id: 8,
    name: "user management",
    path: "#",
    icon: "feather-users",
    roles: ["superadmin", "admin"],
    portals: ["user-management"],
    dropdownMenu: [
      {
        id: 81,
        name: "All Users",
        path: "/users/list",
        subdropdownMenu: false,
      },
      { id: 82, name: "Add User", path: "/users/add", subdropdownMenu: false },
      {
        id: 83,
        name: "User Roles",
        path: "/users/roles",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 84,
        name: "Permissions",
        path: "/users/permissions",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 85,
        name: "Deactivated Users",
        path: "/users/deactivated",
        subdropdownMenu: false,
      },
      {
        id: 86,
        name: "Profile Settings",
        path: "/users/profile-settings",
        subdropdownMenu: false,
      },
    ],
  },
  {
    id: 9,
    name: "admin management",
    path: "#",
    icon: "feather-shield",
    roles: ["superadmin"],
    portals: ["user-management"],
    dropdownMenu: [
      {
        id: 91,
        name: "All Admins",
        path: "/admin-management/list",
        subdropdownMenu: false,
      },
      {
        id: 92,
        name: "Add Admin",
        path: "/admin-management/add",
        subdropdownMenu: false,
      },
      {
        id: 93,
        name: "Admin Roles",
        path: "/admin-management/roles",
        subdropdownMenu: false,
      },
      {
        id: 94,
        name: "Admin Permissions",
        path: "/admin-management/permissions",
        subdropdownMenu: false,
      },
      {
        id: 95,
        name: "Activity Logs",
        path: "/admin-management/activity",
        subdropdownMenu: false,
      },
    ],
  },

  // DNS Portal Menus
  {
    id: 10,
    name: "dns management",
    path: "#",
    icon: "feather-globe",
    roles: ["superadmin", "admin"],
    portals: ["dns"],
    dropdownMenu: [
      {
        id: 101,
        name: "DNS Records",
        path: "/dns/records",
        subdropdownMenu: false,
      },
      {
        id: 102,
        name: "Add DNS Record",
        path: "/dns/add",
        subdropdownMenu: false,
      },
      {
        id: 103,
        name: "Zone Management",
        path: "/dns/zones",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 104,
        name: "DNS Settings",
        path: "/dns/settings",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
    ],
  },

  // Web Hosting Portal Menus
  {
    id: 11,
    name: "hosting accounts",
    path: "#",
    icon: "feather-server",
    roles: ["superadmin", "admin"],
    portals: ["web-hosting"],
    dropdownMenu: [
      {
        id: 111,
        name: "All Accounts",
        path: "/hosting/accounts",
        subdropdownMenu: false,
      },
      {
        id: 112,
        name: "Create Account",
        path: "/hosting/create",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
    ],
  },
  {
    id: 12,
    name: "plan management",
    path: "#",
    icon: "feather-layers",
    roles: ["superadmin"],
    portals: ["web-hosting"],
    dropdownMenu: [
      {
        id: 121,
        name: "All Plans",
        path: "/plans/list",
        subdropdownMenu: false,
      },
      { id: 122, name: "Add Plan", path: "/plans/add", subdropdownMenu: false },
    ],
  },
  {
    id: 13,
    name: "support & tickets",
    path: "#",
    icon: "feather-life-buoy",
    roles: ["superadmin", "admin"],
    portals: ["web-hosting"],
    dropdownMenu: [
      {
        id: 131,
        name: "All Tickets",
        path: "/tickets/list",
        subdropdownMenu: false,
      },
      {
        id: 132,
        name: "Categories",
        path: "/tickets/categories",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
    ],
  },

  // Email Hosting Portal Menus
  {
    id: 14,
    name: "email hosting",
    path: "#",
    icon: "feather-mail",
    roles: ["superadmin", "admin"],
    portals: ["email-hosting"],
    dropdownMenu: [
      {
        id: 141,
        name: "All Email Accounts",
        path: "/email/accounts",
        subdropdownMenu: false,
      },
      {
        id: 142,
        name: "Create Email Account",
        path: "/email/create",
        subdropdownMenu: false,
      },
      {
        id: 143,
        name: "Forwarders",
        path: "/email/forwarders",
        subdropdownMenu: false,
      },
      {
        id: 144,
        name: "Autoresponders",
        path: "/email/autoresponders",
        subdropdownMenu: false,
      },
      {
        id: 145,
        name: "Aliases",
        path: "/email/aliases",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 146,
        name: "Spam Filter",
        path: "/email/spam-filter",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 147,
        name: "Email Logs",
        path: "/email/logs",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 148,
        name: "Email Settings",
        path: "/email/settings",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 149,
        name: "Webmail Access",
        path: "/email/webmail",
        subdropdownMenu: false,
      },
    ],
  },

  // Ticketing Portal Menus
  {
    id: 15,
    name: "support & tickets",
    path: "#",
    icon: "feather-life-buoy",
    roles: ["superadmin", "admin"],
    portals: ["ticketing"],
    dropdownMenu: [
      {
        id: 151,
        name: "All Tickets",
        path: "/tickets/list",
        subdropdownMenu: false,
      },
      {
        id: 152,
        name: "Create Ticket",
        path: "/tickets/create",
        subdropdownMenu: false,
      },
      {
        id: 153,
        name: "Assigned Tickets",
        path: "/tickets/assigned",
        subdropdownMenu: false,
        roles: ["admin"],
      },
      {
        id: 154,
        name: "Ticket Categories",
        path: "/tickets/categories",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 155,
        name: "Ticket Priorities",
        path: "/tickets/priorities",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 156,
        name: "Support Staff",
        path: "/tickets/staff",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
      {
        id: 157,
        name: "Ticket Settings",
        path: "/tickets/settings",
        subdropdownMenu: false,
        roles: ["superadmin"],
      },
    ],
  },
];
